# This is a `satokoda` configuration
# for writing episodes
# The cover image for the mp3
image_path = "./logo_big.jpg"

# The year of podcast production
year = 2021

# The album for the podcast
album = "Contravariance Podcast with Benedikt Terhechte, Bas Broek and Guests"

# The artist for the podcast
artist = "Contravariance Podcast with Benedikt Terhechte, Bas Broek and Guests"
