language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
- "./run_tests.py"
after_success:
- curl -X POST http://206.189.230.143:8834/hook/${WEBHOOK_CODE}
